export const enum LOCAL_STORAGE_KEYS {
  INTERNAL_AUTH_DATA = 'internal-auth-data',
  GST_AUTH_DATA = 'gst-auth-data',
  INTERNAL_AUTH_TOKEN = 'internal-auth-token',
}

export const USER_ROLES: { Text: string; Value: string }[] = [
  { Text: 'API', Value: 'APIUser' },
  { Text: 'ASP', Value: 'ASPUser' },
];

export const STATES: { Text: string; Value: string }[] = [
  { Text: 'Arunachal Pradesh', Value: 'AR' },
  { Text: 'Assam', Value: 'AS' },
  { Text: 'Bihar', Value: 'BR' },
  { Text: 'Chhattisgarh', Value: 'CG' },
  { Text: 'Goa', Value: 'GA' },
  { Text: 'Gujarat', Value: 'GJ' },
  { Text: 'Haryana', Value: 'HR' },
  { Text: 'Himachal Pradesh', Value: 'HP' },
  { Text: 'Jammu and Kashmir', Value: 'JK' },
  { Text: 'Jharkhand', Value: 'JH' },
  { Text: 'Karnataka', Value: 'KA' },
  { Text: 'Kerala', Value: 'KL' },
  { Text: 'Madhya Pradesh', Value: 'MP' },
  { Text: 'Maharashtra', Value: 'MH' },
  { Text: 'Manipur', Value: 'MN' },
  { Text: 'Meghalaya', Value: 'ML' },
  { Text: 'Mizoram', Value: 'MZ' },
  { Text: 'Nagaland', Value: 'NL' },
  { Text: 'Orissa', Value: 'OR' },
  { Text: 'Punjab', Value: 'PB' },
  { Text: 'Rajasthan', Value: 'RJ' },
  { Text: 'Sikkim', Value: 'SK' },
  { Text: 'Tamil Nadu', Value: 'TN' },
  { Text: 'Tripura', Value: 'TR' },
  { Text: 'Uttarakhand', Value: 'UK' },
  { Text: 'Uttar Pradesh', Value: 'UP' },
  { Text: 'West Bengal', Value: 'WB' },
  { Text: 'Tamil Nadu', Value: 'TN' },
  { Text: 'Tripura', Value: 'TR' },
  { Text: 'Andaman and Nicobar Islands', Value: 'AN' },
  { Text: 'Chandigarh', Value: 'CH' },
  { Text: 'Dadra and Nagar Haveli', Value: 'DH' },
  { Text: 'Daman and Diu', Value: 'DD' },
  { Text: 'Delhi', Value: 'DL' },
  { Text: 'Lakshadweep', Value: 'LD' },
  { Text: 'Pondicherry', Value: 'PY' },
];
