export const enum LOCAL_STORAGE_KEYS {
  INTERNAL_AUTH_DATA = 'internal-auth-data',
  GST_AUTH_DATA = 'gst-auth-data',
  INTERNAL_AUTH_TOKEN = 'internal-auth-token',
}

export const USER_ROLES: { Text: string; Value: string }[] = [
  { Text: 'API', Value: 'APIUser' },
  { Text: 'ASP', Value: 'ASPUser' },
];

export const STATES: { Text: string; Value: string }[] = [
  { Text: 'Andhra Pradesh', Value: '37' },
  { Text: 'Arunachal Pradesh', Value: '12' },
  { Text: 'Assam', Value: '18' },
  { Text: 'Bihar', Value: '10' },
  { Text: 'Chhattisgarh', Value: '22' },
  { Text: 'Goa', Value: '30' },
  { Text: 'Gujarat', Value: '24' },
  { Text: 'Haryana', Value: '06' },
  { Text: 'Himachal Pradesh', Value: '02' },
  { Text: 'Jammu and Kashmir', Value: '01' },
  { Text: 'Jharkhand', Value: '20' },
  { Text: 'Karnataka', Value: '29' },
  { Text: 'Kerala', Value: '32' },
  { Text: 'Madhya Pradesh', Value: '23' },
  { Text: 'Maharashtra', Value: '27' },
  { Text: 'Manipur', Value: '14' },
  { Text: 'Meghalaya', Value: '17' },
  { Text: 'Mizoram', Value: '15' },
  { Text: 'Nagaland', Value: '13' },
  { Text: 'Odisha', Value: '21' },
  { Text: 'Punjab', Value: '03' },
  { Text: 'Rajasthan', Value: '08' },
  { Text: 'Sikkim', Value: '11' },
  { Text: 'Tamil Nadu', Value: '33' },
  { Text: 'Telangana', Value: '36' },
  { Text: 'Tripura', Value: '16' },
  { Text: 'Uttar Pradesh', Value: '09' },
  { Text: 'Uttarakhand', Value: '05' },
  { Text: 'West Bengal', Value: '19' },
  { Text: 'Andaman and Nicobar Islands', Value: '35' },
  { Text: 'Chandigarh', Value: '04' },
  { Text: 'Dadra and Nagar Haveli and Daman and Diu', Value: '26' },
  { Text: 'Delhi', Value: '07' },
  { Text: 'Ladakh', Value: '38' },
  { Text: 'Lakshadweep', Value: '31' },
  { Text: 'Puducherry', Value: '34' },
];
